# Generated by Django 4.1.7 on 2023-05-31 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('user_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
