# Generated by Django 4.1.7 on 2023-05-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_uploadedfile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
