# Generated by Django 2.2.4 on 2023-08-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exp', models.TextField()),
                ('image', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('price_str', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('vos', models.CharField(max_length=100)),
                ('ram', models.FloatField(null=True)),
                ('cpu', models.FloatField(null=True)),
                ('browers', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(to='documents.Category')),
            ],
        ),
    ]
