# Generated by Django 2.2.4 on 2023-08-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vaccine',
            name='hdd',
            field=models.FloatField(null=True),
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='vos',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='vos',
            field=models.ManyToManyField(to='documents.Vos'),
        ),
    ]
