# Generated by Django 2.2.4 on 2023-08-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20230823_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='browers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vos',
            name='vc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Vaccine'),
        ),
    ]
