# Generated by Django 2.2.4 on 2023-08-24 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20230824_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='a_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vos',
            name='vc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Vaccine'),
        ),
    ]
